name: Continous Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCW_TOKEN }}
        registry: ${{ secrets.SCW_REGISTRY }}
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.SCW_REGISTRY }}/ae-data-processing:latest
    - name: Push the Docker Image
      run: docker push ${{ secrets.SCW_REGISTRY }}/ae-data-processing:latest
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: yarn install --frozen-lockfile
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: -c "serverless plugin install --name serverless-scaleway-functions && serverless deploy"
        entrypoint: /bin/sh
      env:
        SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
        SCW_TOKEN: ${{ secrets.SCW_TOKEN }}
        SCW_REGISTRY: ${{ secrets.SCW_REGISTRY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        MONGO_DATABASE: ${{ vars.MONGO_DATABASE }}
        SCW_BUCKET: ${{ vars.SCW_BUCKET }}
        SCW_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY_ID }}
        SCW_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_ACCESS_KEY }}
        SCW_ENDPOINT: ${{ vars.SCW_ENDPOINT }}
        SCW_REGION: ${{ vars.SCW_REGION }}
